### ISSUE TITLE
关于「9.4.3 写入角色与权限」小节有关代码设计的讨论

### ISSUE THREAD

**Issue by AngelLiang** [greyli/albumy#1]
首先，「Albumy程序中定义的角色及对应权限」表格有六个角色（`Guest`、`Blokced`、`Locked`、`User`、`Moderator`、`Administrator`），然后转换为下面的字典，功能上是没有问题的。

```Python
roles_permissions_map = {
    'Locked': ['FOLLOW', 'COLLECT'],
    'User': ['FOLLOW', 'COLLECT', 'COMMENT' 'UPLOAD'],
    'Moderator': ['FOLLOW', 'COLLECT', 'COMMENT', 'UPLOAD', 'MODERATE'],
    'Administrator': ['FOLLOW', 'COLLECT', 'COMMENT', 'UPLOAD', 'MODERATE', 'ADMINISTER']
     }
```

但是，在设计风格上，我觉得上面的字典没有完全体现出设计者的设计思路，也就是定义好的所有角色与权限。

这个问题，有点类似于数据库中的字符串字段如果为空，应该设置为`NULL`好还是空字符串`""`好。

如果我来设计，会把`Guest`和`Blokced`也加上去，但是，value为`[]`：

```Python
roles_permissions_map = {
    'Guest': [],
    'Blokced': [],
    'Locked': ['FOLLOW', 'COLLECT'],
    'User': ['FOLLOW', 'COLLECT', 'COMMENT' 'UPLOAD'],
    'Moderator': ['FOLLOW', 'COLLECT', 'COMMENT', 'UPLOAD', 'MODERATE'],
    'Administrator': ['FOLLOW', 'COLLECT', 'COMMENT', 'UPLOAD', 'MODERATE', 'ADMINISTER']
     }
```

这样在代码层次上，就能体现出还有**访客**和**被封禁用户**这两个角色，只不过这两个角色什么权限也没有。

当然，考虑到后面的代码会把字典的`key`加入数据库，如果不希望添加到数据库或是别的原因，可以对之进行注释（而不是从代码里删除）：

```Python
roles_permissions_map = {
    # 'Guest': [],
    # 'Blokced': [],
    'Locked': ['FOLLOW', 'COLLECT'],
    'User': ['FOLLOW', 'COLLECT', 'COMMENT' 'UPLOAD'],
    'Moderator': ['FOLLOW', 'COLLECT', 'COMMENT', 'UPLOAD', 'MODERATE'],
    'Administrator': ['FOLLOW', 'COLLECT', 'COMMENT', 'UPLOAD', 'MODERATE', 'ADMINISTER']
     }
```

以上是我想表达的观点：「代码应尽量完全表达设计者的思路」。这样其他人一看到这个字典，喔~设计者定义了六个角色，有这些那些权限。而不是一看代码，设计者好像只定义了四个角色，有这些那些权限，然后去看设计文档，原来是六个角色（正如书中必须写点提示，解释为什么代码里没有另外两个角色）。

一点小小的探讨，如有不妥，还请见谅。

**Comment by greyli** [comment]
谢谢，我很赞同你的观点，这里的确有必要添加关于这两个“隐藏”角色的注释。

书里的几个项目，尤其是后四个，因为同时要兼顾书稿的写作，编写的比较仓促，一些地方在设计和实现上没有深入考虑。另外，因为同时编写程序和书稿，书稿的内容解释了程序的实现，但是因为没有单独站在程序的角度来思考具体实现，所以代码里缺少一些必要的注释。

我计划在helloflask仓库添加一个improvement.md文件，存储这些程序中可以改进的地方。

**Comment by greyli** [comment]
在helloflask仓库创建了一个“可改进实现”文件，把你的建议放进去了（[具体位置](https://github.com/greyli/helloflask/blob/master/improvement/improvement.md#943-%E5%86%99%E5%85%A5%E7%94%A8%E6%88%B7%E6%9D%83%E9%99%90%E4%B8%AD%E7%9A%84%E8%A7%92%E8%89%B2%E4%B8%8E%E6%9D%83%E9%99%90%E5%AD%97%E5%85%B8%E7%9A%84%E8%AE%BE%E8%AE%A1)）。目前这个文件的最佳编写格式还不确定，你随时可以创建PR修改它。

**Comment by AngelLiang** [comment]
感谢你的认同和回复。
