### ISSUE TITLE
在消息提醒notification.py文件中的问题

### ISSUE THREAD

**Issue by nishizhumagu** [greyli/albumy#19]
我自己按照书中的提示在自行编写了新用户注册时发送消息提醒函数如下：
`def push_confirm_notification(register):`
    `reciver = User.query.filter_by(pl_num=current_app.config['ADMIN_PL_NUM']).first()`
    `message = '用户<a href="%s">%s</a>已注册' % (url_for("main.show_user", user_id=register.id), register.name)`
    `notification = Notification(message=message, reciver_id=reciver.id)`
    `db.session.add(notification)`
    `db.session.commit()`
    `db.session.close()`

但是每次注册新用户时总会出现错误，提示我werkzeug.routing.BuildError: Could not build url for endpoint 'main.show_user'. Did you forget to specify values ['user_id']?
请问这是什么原因导致的呢？希望大神给解答。

**Comment by greyli** [comment]
请提供 show_user 视图函数的定义。

**Comment by greyli** [comment]
后续和项目源码无关的问题可以发到 [helloflask 仓库](https://github.com/greyli/helloflask)或是 [HelloFlask 论坛](https://discuss.helloflask.com)。

**Comment by greyli** [comment]
已在 QQ 群讨论解决。问题的原因是传入的 register 记录对象还没有提交到数据库，所以不会有 id 属性值。
