### ISSUE TITLE
Photo下无法关闭评论

### ISSUE THREAD

**Issue by Shimada666** [greyli/albumy#2]
自己图片下disabled comment会

Method Not Allowed

The method is not allowed for the requested URL.

**Comment by greyli** [comment]
感谢反馈！这里是个疏漏，模板里设置评论开启关闭的按钮应该编写成表单，使用POST方法提交请求。我待会更正到master分支，并添加到勘误。

**Comment by greyli** [comment]
谢谢，临时在master分支修复了（[4ef2898](https://github.com/greyli/albumy/commit/4ef28988586fc09a64e31b87722b83615416b1cd)）。
