### ISSUE TITLE
admin@helloflask.com无法登录

### ISSUE THREAD

**Issue by skgone** [greyli/albumy#27]
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: user.avatar_s [SQL: 'SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.name AS user_name, user.website AS user_website, user.bio AS user_bio, user.location AS user_location, user.member_since AS user_member_since, user.avatar_s AS user_avatar_s, user.avatar_m AS user_avatar_m, user.avatar_l AS user_avatar_l, user.avatar_raw AS user_avatar_raw, user.confirmed AS user_confirmed, user.locked AS user_locked, user.active AS user_active, user.public_collections AS user_public_collections, user.receive_comment_notification AS user_receive_comment_notification, user.receive_follow_notification AS user_receive_follow_notification, user.receive_collect_notification AS user_receive_collect_notification, user.role_id AS user_role_id \nFROM user \nWHERE user.email = ?\n LIMIT ? OFFSET ?'] [parameters: ('admin@helloflask.com', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by greyli** [comment]
看报错是没有创建数据库表？执行 flask initdb 命令试试。

**Comment by skgone** [comment]
初始化数据库后，可以登入了。谢谢
