### ISSUE TITLE
仓库中代码与书中描述不匹配

### ISSUE THREAD

**Issue by chenyz1984** [greyli/albumy#32]
书中第304页，按注意中git checkout skeleton签出程序后，代码结构与304-305页显示的程序包目录结构不一致。
![图片](https://user-images.githubusercontent.com/20869868/72244141-92572d80-3628-11ea-986d-1ca29f660a48.png)
在第8章的个人博客部分也存在此情况。

**Comment by greyli** [comment]
书里给出的程序文件结构是最终的程序文件结构，而不是 skeleton 标签对应的程序文件结构。

**Comment by greyli** [comment]
签出提示放到这一段介绍项目文件结构的内容后面就可以避免歧义了，感谢反馈，会在第二版修正。
