### ISSUE TITLE
没有wsgi，执行flask是怎么找到app的

### ISSUE THREAD

**Issue by hjokerkevin** [greyli/albumy#38]
我自己写了一份，执行flask的时候会报找不到app，然后commands参数没有显示我增加的那些。

**Comment by greyli** [comment]
`flask`  命令会从环境变量 `FLASK_APP` 读取程序路径，详细规则见文档 [Application Discovery](https://flask.palletsprojects.com/en/1.1.x/cli/#application-discovery) 一章。

如果安装了 python-dotenv，那么 Flask 从会 .flaskenv 和 .env 文件里读取环境变量。这个程序的 `FLASK_APP`  环境变量就定义在 [.flaskenv 文件](https://github.com/greyli/albumy/blob/master/.flaskenv) 里。
