### ISSUE TITLE
评论回复问题

### ISSUE THREAD

**Issue by gweid** [greyli/albumy#4]
1、当没有评论的时候，新建一条评论提交会跳转404（找不到页面），url中显示page=0
     应该是 _comment.html 中的：
     _<div class="comment-form" id="comment-form">
               {{ render_form(comment_form, action=url_for('.new_comment', photo_id=photo.id, 
                           page=pagination.pages),extra_classes="text-right") }}
      </div>_
      这一片段，应为 page=pagination.pages or 1
2、评论回复功能实现不了，只能生成新评论；
3、当是自己的评论时，个人觉得不应该有举报按钮，不能自己举报自己
谢谢

**Comment by greyli** [comment]
感谢反馈。因为时间仓促，程序有些地方设计的不够完善。周末我会一一确定和完善。

**Comment by goodbad3** [comment]
数据库中replied_id显示null，按第8章那个回复弄了一下午，整个不能运行了

**Comment by gweid** [comment]
> 数据库中replied_id显示null，按第8章那个回复弄了一下午，整个不能运行了

是的，replied_id是null,应该是new_comment跳到show_photo那地方出错了，

**Comment by goodbad3** [comment]
reply_comment好像有问题，

**Comment by goodbad3** [comment]
它跳不到new_commment中

**Comment by greyli** [comment]
Fixed in [fcbcd01](https://github.com/greyli/albumy/commit/fcbcd0150d599e8187e201af2fcb8da3ca09ebce).

**Comment by gweid** [comment]
> Fixed in [fcbcd01](https://github.com/greyli/albumy/commit/fcbcd0150d599e8187e201af2fcb8da3ca09eb

> Fixed in [fcbcd01](https://github.com/greyli/albumy/commit/fcbcd0150d599e8187e201af2fcb8da3ca09ebce).

感谢你的回复
评论与回复功能如果可以的话，应该做得精致点，比如：每条回复都显示在对应的评论下面

**Comment by greyli** [comment]
因为只是示例程序，比较简单，后续会考虑优化。先关闭了。

**Comment by gweid** [comment]
好的，感谢您的回复

Grey Li <notifications@github.com> 于2018年12月3日周一 下午5:14写道：
