### ISSUE TITLE
utils模块中itsdangerours库的 TimedJsonWebSignatureSerializer 已经弃用，应该替换成什么？

### ISSUE THREAD

**Issue by nelande** [greyli/albumy#52]
在utils模块中，验证邮箱地址生成令牌这一部分的代码
TimedJsonWebSignatureSerializer 已经被itsdangerous弃用了，参见itsdangerous的更新日志
那么现在应该使用什么类或者什么库替代？怎么使用?

**Comment by greyli** [comment]
可以考虑用 Authlib 的 jose 模块，参考这里的用法：

https://github.com/apiflask/apiflask/blob/main/examples/auth/token_auth/app.py

后续我会对这个示例做一些改进。
