### ISSUE TITLE
关于权限过滤、搜索和个人主页的改进

### ISSUE THREAD

**Issue by gweid** [greyli/albumy#7]
一、个人主页
   1、个人主页收藏处没有显示页码
二、搜索问题
   1、输入空格搜索会出现BUG
三、管理员与协管员问题
   1、在后台处，当登陆用户为管理员或者协管员时，后台用户管理处自己不应该能锁定或封禁自己，不然可能会不小心把自己给锁定或者封禁了
   2、协管员权限过大，应该过滤一下，不然连超级管理员都能锁定、封禁
谢谢！

**Comment by goodbad3** [comment]
1、在后台处，当登陆用户为管理员或者协管员时，后台用户管理处不应该出现自己，不然可能会不小心把自己给锁定或者封禁了
这个我尝试过，己给锁定或者封禁了

**Comment by greyli** [comment]
感谢反馈，有时间会更新。

**Comment by GrootBie** [comment]
uplaod 按钮看不到

**Comment by taodejin** [comment]
有时间可以在图片下方加一个下载功能啊

**Comment by taodejin** [comment]
发现了一个问题，就是在，我没有登陆的时候，我点击图片，然后收藏这个图片或者关注这个人，会重定向到登陆页面，然后我再登陆之后，你会发现他报错了，方法不被允许，没有重新定向到这个收藏界面或者关注这个人。

**Comment by greyli** [comment]
@taodejin 请参考 #13 。另外，后续有新问题请单独新创建 Issue。

**Comment by greyli** [comment]
> 个人主页收藏处没有显示页码

已修复： https://github.com/greyli/albumy/commit/d51b5ed6ecbe00f5dff9cfcba5bad91d57a953fe

> 输入空格搜索会出现BUG

已修复： https://github.com/greyli/albumy/commit/5f679d8eab9ba5b35fc30128df344a28b7cd2af8

> 管理员与协管员问题

已修复： https://github.com/greyli/albumy/commit/943829b819b7bda6921d6c0fe277c75cd6a98033

感谢反馈！
