### ISSUE TITLE
没有显示upload按钮

### ISSUE THREAD

**Issue by GrootBie** [greyli/albumy#9]
没有显示upload按钮

**Comment by greyli** [comment]
请问你说的”upload 按钮“具体指什么？导航栏上面有打开上传页面的图标。

**Comment by GrootBie** [comment]
在你的demo地址上，upload 按钮图标是被隐藏状态
![image](https://user-images.githubusercontent.com/45776914/49780748-e703e700-fd4a-11e8-8820-19612794e05a.png)

**Comment by greyli** [comment]
没有隐藏，只是图标没有加载出来，可以刷新试试。建议在本地安装运行程序进行测试，demo 做了一些修改，不支持上传功能。
